site_name: Kiln
site_url: https://ashvin.au
site_description: Kiln - Digital twins for product managers
repo_url: https://github.com/sarantium/ashvin/
repo_name: sarantium/ashvin
theme:
  name: material
  icon:
    logo: material/view-grid-plus
  favicon: assets/view-grid-plus-outline-dark.png
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.indexes
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.footer
    - navigation.top

plugins:
  - search
  - meta
  - blog:
      archive: true
      archive_name: History
      pagination_per_page: 10
      post_readtime: true
      post_url_format: "{date}/{slug}"
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sarantium/ashvin
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ashvinparameswaran
    - icon: fontawesome/solid/file-pdf
      link: /assets/ashvin_parameswaran_curriculum_vitae_2023.pdf
      name: resume

copyright: Copyright &copy; 2023-2025 Ashvin Parameswaran

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: ⚓︎
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

nav:
  - Twins and Agents: README.md
  - Loops and Documents: concepts.md
  - Creativity and Productivity: creativity.md
  - State of AI Product 2024:
      - Ideas: stateofaiproduct2024.md
      - Prompts: prompts.md
  - Books and Papers: research.md
  - Dreams and Hallucinations:
      - blog/index.md
