[project]
name = "ashvin"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.6.21",
    "youtube-transcript-api>=1.2.3",
]
